### ISSUE TITLE
SGHMC does not work for simulated logistic regression

### ISSUE THREAD

**Issue by modestbayes** [STOR-i/sgmcmc#1]
I was trying to run SGHMC on a logistic regression model with 100,000 x 50 simulated data but the algorithm would not converge unless I set the stepsize to very small i.e. 5e-10. Then the posteriors would just be way off from the true posteriors (true betas are randomly chosen between -1 and 1). Would you please give me some insights on this? Thank you very much!

**Comment by linggeli7** [comment]
Also, I think if you run standard HMC on the covertype data, the posterior would not be "well defined" in the sense that design matrix is collinear and the distribution shape is very "stretched out" (ill-conditioned). Therefore, I think the demo could be problematic.

**Comment by jackcbaker** [comment]
Hello linggeli7, sorry for the slow reply on this. Does SGLD converge correctly on your example set?

If you attach the code generating the dataset I can take a closer look. If the data is not scaled then gradient based methods can sometimes work quite badly.
